# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a2efcbba75c92fd505ab879867ab9e4de610ab93b257f13b2d1bb6c53d53e56c22da6bd31fb316bcc26b60f99708c9eb47fac24901751eba6809032a01ab638

test:
  secret_key_base: 9642c0beebf64aa832fb66732c6a9cde77a2759b35e71eb1842ed8c8520f44c42a31d4704f393c829b016024de50207d56be49b4609aeb89b461cfa489e2a58d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
